name: book
channels:
  - pytorch
  - defaults
  - pyg
  - conda-forge
  - nvidia
dependencies:
  - python=3.9
  - cudatoolkit=11.7
  - pytorch-cuda=11.7
  - pytorch-scatter
  - pip
  - notebook
  - ipykernel
  - ipywidgets
  - git-lfs
  - libsndfile
  - pip:
      - -r requirements.txt
